[package]
name = "caisin"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Caisin/caisin-rs.git"
description = "caisin tools"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
serde = "1.0.144"
serde_json = "1.0.85"
