[package]
name = "caisin"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Caisin/caisin-rs.git"
description = "caisin tools"
license = "caisin"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
